import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:sistem_pakar/controllers/controller.dart';
import 'package:sistem_pakar/models/gejala.dart';
import 'package:sistem_pakar/models/results.dart';
import 'package:sistem_pakar/models/penyakit.dart';
import 'package:sistem_pakar/presentation/shared/theme.dart';
import 'package:sistem_pakar/presentation/ui/widgets/widgets.dart';
import 'package:carousel_slider/carousel_slider.dart';

part 'home_page.dart';
part 'pilih_pakar_page.dart';
part 'pertanyaan_page.dart';
part 'hasil_page.dart';
part 'info_penyakit_page.dart';
part 'detail_penyakit_page.dart';
part 'tutorial_page.dart';
part 'tentang_page.dart';
